name: build-hello-world.yml
on:
  push:
    branches:
      - main
    paths:
      - hello-world
      - .github/workflows/build-hello-world.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run mvn
        run: mvn clean install
        working-directory: hello-world

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}